name = "ycar601"
compatibility_date = "2026-08-27"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "ycar601-production"
database_id = "8e5a646b-fc27-4536-9b11-f65a26237535"
preview_database_id = "4eff553d-95e9-4153-9c2e-68aee18ac370"

[[r2_buckets]]
binding = "FILES"
bucket_name = "ycar601-private-files"

[vars]
AUTH_MODE = "cloudflare-access"
VAPID_PUBLIC_KEY = ""
ALLOW_DEMO_AUTH = "false"
ALLOW_ANONYMOUS_WRITES = "false"
DEVICE_AUTH_ENABLED = "false"
GOOGLE_SHEET_AUTO_SYNC_TAB = ""
