export const zones = [
  { id: 'pillar11', name: '서서울모터리움 6층', short: '6층', type: 'parking', count: 70 }, { id: 'roof', name: '서서울모터리움 옥상층', short: '옥상', type: 'parking', count: 0 },
  { id: 'tower', name: '좋은책신사고 새싹타워', short: '새싹', type: 'parking', count: 10 }, { id: 'auto13', name: '오토플렉스 13층', short: '13층', type: 'parking', count: 12 },
  { id: 'polish', name: '광택', short: '광택', type: 'service', count: 4 }, { id: 'body', name: '판금', short: '판금', type: 'service', count: 4 }, { id: 'repair', name: '정비', short: '정비', type: 'service', count: 4 }
];
const models=['쏘나타','그랜저','아반떼','카니발','스포티지','투싼','K5','셀토스'], colors=['흰색','검정','은색','회색','파랑'];
const plates=['186저9439','332거4844','104누5036','56거2704','289무7006','169무1539','167조3574','383다3500','257저9955','25나5633','51보1818','242부9198','170누6876','56마7937','50고3422','210부1269'];
export const STATUS=[{id:'coolant-low',label:'냉각수부족경고등',mark:'냉',icon:'냉각수부족경고등.png'},{id:'light',label:'라이트경고등',mark:'L',icon:'라이트경고등.png'},{id:'battery',label:'배터리경고등',mark:'B',icon:'배터리경고등.png'},{id:'engine',label:'엔진경고등',mark:'E',icon:'엔진경고등.png'},{id:'engine-oil-low',label:'엔진오일부족경고등',mark:'오',icon:'엔진오일부족경고등.png'},{id:'oil-pressure',label:'엔진오일압력경고등',mark:'압',icon:'엔진오일압력경고등.png'},{id:'urea',label:'요소수경고등',mark:'U',icon:'요소수경고등.png'},{id:'fuel',label:'주유경고등',mark:'F',icon:'주유경고등.png'},{id:'tire',label:'타이어공기압 경고등',mark:'T',icon:'타이어공기압.png'},{id:'master-warning',label:'통합경고등',mark:'!',icon:'통합경고등.png'},{id:'abs',label:'ABS경고등',mark:'A',icon:'ABS경고등.png'}];
export function makeInitialSpots(){let cursor=0;return zones.flatMap((z,zi)=>Array.from({length:z.count},(_,i)=>{const used=z.type==='service'?i<2:(cursor++*7+zi*3)%10<7, cols=z.type==='service'?4:z.id==='pillar11'?6:z.id==='tower'?10:4, seed=(i+zi*3)%plates.length;return{id:`${z.id}-${i+1}`,zoneId:z.id,zone:z.name,zoneShort:z.short,label:`${String.fromCharCode(65+(i%cols))}${Math.floor(i/cols)+1}`,plate:used?plates[seed]:'',model:used?models[(i+zi)%models.length]:'',color:used?colors[(i*2+zi)%colors.length]:'',alerts:used&&i%7===1?[STATUS[(i+zi)%STATUS.length].id]:[],memo:z.type==='service'&&used?`${z.name} 작업 중`:'',enteredAt:used?'2026-08-27 09:20':'',updatedAt:'오늘 14:20'};}));}
